server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
#      default-filters:
#        - name: RateLimitFilter
      routes:
        - id: web
          uri: lb://WEB
          predicates:
            - Path=/web/**
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

logging:
  level:
    root: debug

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka